# Generated by Django 5.2.6 on 2025-09-29 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="comment",
        ),
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                default=None,
                help_text="Укажите пост для комментирования",
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.post",
                verbose_name="Пост",
            ),
        ),
    ]
